// Shared demo job data — Kenya-localized (KSh salaries, local cities).
// Mix of large companies and SMEs across Nairobi, Mombasa, Kisumu, Thika, Nakuru.
// International / remote roles explicitly use location: "Remote" and type: "Remote".

const demoJobs = [
  {
    _id: "d1",
    title: "Senior Software Engineer",
    company: { companyName: "Safaricom PLC", companyLogo: "" },
    location: "Nairobi, Kenya",
    type: "Full-Time",
    category: "IT & Software",
    salaryMin: 180000,
    salaryMax: 280000,
    experience: "5+ years",
    status: "Applied",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Safaricom is looking for a Senior Software Engineer to build and scale the next generation of M-PESA payment infrastructure and digital services used by millions of Kenyans every day.",
    responsibilities: [
      "Design and implement scalable microservices powering M-PESA and Safaricom APIs.",
      "Collaborate with product and design teams to ship customer-facing features.",
      "Lead code reviews and mentor mid-level and junior engineers.",
      "Define technical architecture for new platform initiatives.",
      "Monitor system health and drive incident response processes.",
    ],
    requirements: [
      "5+ years of backend software development experience.",
      "Strong proficiency in Java, Go, or Node.js.",
      "Experience with event-driven systems and message queues (Kafka, RabbitMQ).",
      "Solid understanding of distributed systems design and REST API best practices.",
      "Fintech or payments domain experience is a strong plus.",
    ],
  },
  {
    _id: "d2",
    title: "Full-Stack Web Developer",
    company: { companyName: "Nairobi Tech Hub (SME)", companyLogo: "" },
    location: "Nairobi, Kenya",
    type: "Full-Time",
    category: "IT & Software",
    salaryMin: 80000,
    salaryMax: 130000,
    experience: "2+ years",
    status: "open",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Nairobi Tech Hub is a fast-growing SME building SaaS solutions for the East African market. We need a hands-on Full-Stack Developer to own both frontend and backend features on our client management platform.",
    responsibilities: [
      "Build and maintain features across a React frontend and Node.js/Express backend.",
      "Design and query PostgreSQL databases for performance and reliability.",
      "Integrate third-party APIs including M-PESA Daraja and Africa's Talking.",
      "Deploy applications on AWS using Docker and CI/CD pipelines.",
      "Participate in client requirement workshops and translate them into technical specs.",
    ],
    requirements: [
      "2+ years of full-stack development experience.",
      "Solid knowledge of React, Node.js, and SQL.",
      "Experience integrating payment or telecoms APIs in the Kenyan market.",
      "Self-starter who can work with minimal supervision in an SME environment.",
      "Good communication skills; comfortable presenting to non-technical clients.",
    ],
  },
  {
    _id: "d3",
    title: "UI/UX Product Designer",
    company: { companyName: "Cellulant Africa", companyLogo: "" },
    location: "Nairobi, Kenya",
    type: "Full-Time",
    category: "Design",
    salaryMin: 120000,
    salaryMax: 190000,
    experience: "3+ years",
    status: "open",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Cellulant is hiring a UI/UX Product Designer to own the end-to-end experience of its pan-African payments platform, ensuring clarity and delight for merchants and consumers across 18 markets.",
    responsibilities: [
      "Lead product design from discovery research through high-fidelity Figma prototypes.",
      "Conduct usability testing with real merchants and consumers across East Africa.",
      "Build and maintain a cohesive cross-platform design system.",
      "Partner closely with engineering to ensure pixel-accurate implementation.",
      "Present design decisions to stakeholders and iterate based on feedback.",
    ],
    requirements: [
      "3+ years of product design experience on a digital product.",
      "Expert proficiency in Figma and prototyping tools.",
      "Portfolio demonstrating end-to-end UX process and visual polish.",
      "Experience designing for both web and mobile (iOS/Android).",
      "Familiarity with accessibility standards (WCAG 2.1).",
    ],
  },
  {
    _id: "d4",
    title: "Graphic Designer & Brand Officer",
    company: { companyName: "Kisumu Creative Studio (SME)", companyLogo: "" },
    location: "Kisumu, Kenya",
    type: "Full-Time",
    category: "Design",
    salaryMin: 45000,
    salaryMax: 75000,
    experience: "2+ years",
    status: "open",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Kisumu Creative Studio is a boutique design agency serving local businesses, NGOs, and county government clients across Western Kenya. We need a versatile designer to lead brand identity and digital content projects.",
    responsibilities: [
      "Design logos, brand identity kits, and marketing materials for SME clients.",
      "Create social media content calendars and graphics for client campaigns.",
      "Produce print-ready artwork for billboards, brochures, and merchandise.",
      "Support video editing and motion graphics for short-form social content.",
      "Manage client relationships and present concepts in review meetings.",
    ],
    requirements: [
      "2+ years of graphic design experience in an agency or in-house role.",
      "Proficiency in Adobe Illustrator, Photoshop, and InDesign.",
      "Strong portfolio of brand identity and marketing design work.",
      "Video editing experience (Premiere Pro or DaVinci Resolve) is a plus.",
      "Ability to manage multiple client briefs simultaneously under tight deadlines.",
    ],
  },
  {
    _id: "d5",
    title: "Digital Marketing Manager",
    company: { companyName: "Jumia Kenya", companyLogo: "" },
    location: "Nairobi, Kenya",
    type: "Full-Time",
    category: "Marketing",
    salaryMin: 100000,
    salaryMax: 150000,
    experience: "4+ years",
    status: "open",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Jumia Kenya is seeking a Digital Marketing Manager to drive customer acquisition and retention through data-driven campaigns across search, social, email, and performance channels.",
    responsibilities: [
      "Plan and execute multi-channel digital campaigns aligned to sales targets.",
      "Manage a monthly paid media budget across Google Ads and Meta platforms.",
      "Analyse funnel performance and surface actionable optimisation insights.",
      "Collaborate with the creative team to produce compelling ad content.",
      "Report weekly on KPIs to the Country Marketing Director.",
    ],
    requirements: [
      "4+ years of digital marketing experience in an e-commerce environment.",
      "Hands-on expertise with Google Analytics 4, Google Ads, and Meta Ads Manager.",
      "Proven track record of scaling paid acquisition profitably.",
      "Strong copywriting and A/B testing skills.",
      "Experience working in a fast-paced, data-driven team.",
    ],
  },
  {
    _id: "d6",
    title: "Social Media & Content Executive",
    company: { companyName: "Thika Road Motors (SME)", companyLogo: "" },
    location: "Thika, Kenya",
    type: "Part-Time",
    category: "Marketing",
    salaryMin: 30000,
    salaryMax: 50000,
    experience: "1+ year",
    status: "open",
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Thika Road Motors is a family-owned auto dealership and service centre looking for a part-time Social Media Executive to grow its online presence on Instagram, Facebook, and TikTok.",
    responsibilities: [
      "Create and schedule daily content across Facebook, Instagram, and TikTok.",
      "Photograph and film vehicles, workshop activities, and customer testimonials.",
      "Respond to DMs and comments to build community engagement.",
      "Run boosted post campaigns with a small monthly budget.",
      "Report on reach, engagement, and lead generation metrics weekly.",
    ],
    requirements: [
      "1+ year managing business social media accounts.",
      "Comfortable with smartphone photography and basic video editing (CapCut/Reels).",
      "Outgoing personality with strong written Kiswahili and English skills.",
      "Basic understanding of Meta Ads Manager.",
      "Own transport to visit the Thika showroom twice a week.",
    ],
  },
  {
    _id: "d7",
    title: "Data Analyst",
    company: { companyName: "Kenya Revenue Authority", companyLogo: "" },
    location: "Nairobi, Kenya",
    type: "Contract",
    category: "Finance",
    salaryMin: 90000,
    salaryMax: 130000,
    experience: "2+ years",
    status: "Applied",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "KRA is contracting a Data Analyst to analyse tax compliance datasets, develop dashboards for leadership, and support evidence-based policy decisions across the authority.",
    responsibilities: [
      "Write advanced SQL queries to extract, clean, and analyse large taxpayer datasets.",
      "Build self-service dashboards in Power BI for operational and executive audiences.",
      "Identify compliance trends and anomalies that inform audit targeting.",
      "Document analytical methodologies and data dictionaries.",
      "Present findings clearly to non-technical commissioners and directors.",
    ],
    requirements: [
      "2+ years of data analysis experience in finance or government.",
      "Advanced SQL and proficiency in Excel/Power BI.",
      "Python or R skills are a bonus.",
      "Strong attention to detail and ability to handle sensitive data.",
      "Knowledge of Kenyan tax legislation is advantageous.",
    ],
  },
  {
    _id: "d8",
    title: "React Frontend Developer",
    company: { companyName: "Andela (Kenya Hub)", companyLogo: "" },
    location: "Remote",
    type: "Remote",
    category: "Engineering",
    salaryMin: 150000,
    salaryMax: 220000,
    experience: "3+ years",
    status: "open",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Andela is placing a Remote React Frontend Developer on a global product team. You will build fast, accessible interfaces that serve users across the US, Europe, and Africa.",
    responsibilities: [
      "Build responsive, accessible UI components in React and TypeScript.",
      "Collaborate asynchronously with distributed product and design teams.",
      "Write comprehensive unit and integration tests with Jest and Testing Library.",
      "Participate in performance reviews targeting Core Web Vitals.",
      "Contribute to shared component libraries and front-end architecture decisions.",
    ],
    requirements: [
      "3+ years of React production experience.",
      "Strong TypeScript and modern CSS (Tailwind / CSS Modules) skills.",
      "Experience with state management (Redux Toolkit, Zustand, or React Query).",
      "Ability to work in overlapping time-zone schedules with US/EU teams.",
      "Strong written English communication skills.",
    ],
  },
  {
    _id: "d9",
    title: "Cybersecurity Analyst",
    company: { companyName: "Sanlam Kenya", companyLogo: "" },
    location: "Mombasa, Kenya",
    type: "Full-Time",
    category: "IT & Software",
    salaryMin: 110000,
    salaryMax: 165000,
    experience: "3+ years",
    status: "open",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Sanlam Kenya is looking for a Cybersecurity Analyst to protect the firm's digital assets and customer data, manage security operations, and ensure regulatory compliance across insurance and investment platforms.",
    responsibilities: [
      "Monitor SIEM dashboards and investigate security alerts in real time.",
      "Conduct vulnerability assessments and penetration tests quarterly.",
      "Maintain and update incident response and disaster recovery playbooks.",
      "Liaise with the CBK and IRA on cybersecurity compliance reporting.",
      "Deliver security awareness training to staff across all branches.",
    ],
    requirements: [
      "3+ years in a cybersecurity or information security role.",
      "CEH, CISSP, or CompTIA Security+ certification preferred.",
      "Hands-on experience with SIEM tools (Splunk, IBM QRadar, or similar).",
      "Solid understanding of network security, firewalls, and endpoint protection.",
      "Knowledge of Kenya's Data Protection Act 2019.",
    ],
  },
  {
    _id: "d10",
    title: "Software Engineering Intern",
    company: { companyName: "Moringa School", companyLogo: "" },
    location: "Nairobi, Kenya",
    type: "Internship",
    category: "Engineering",
    salaryMin: 25000,
    salaryMax: 40000,
    experience: "0–1 year",
    status: "open",
    createdAt: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Moringa School is offering a 3-month Software Engineering Internship for recent graduates or final-year students. You will contribute to internal learning tools while being mentored by senior engineers.",
    responsibilities: [
      "Develop and maintain features on Moringa's student learning management platform.",
      "Write clean, well-tested code in React (frontend) and Django (backend).",
      "Attend daily stand-ups and biweekly retrospectives with the engineering team.",
      "Document technical decisions and update internal wikis.",
      "Participate in weekly code-review sessions with a senior mentor.",
    ],
    requirements: [
      "Currently enrolled in or recently graduated from a CS, IT, or Software Engineering programme.",
      "Foundational knowledge of HTML, CSS, JavaScript, and Python.",
      "Eagerness to learn, receive feedback, and grow quickly.",
      "Ability to commit to a 3-month full-time in-person programme in Nairobi.",
      "Portfolio project or GitHub profile to showcase prior work.",
    ],
  },
  {
    _id: "d11",
    title: "Agribusiness Sales Representative",
    company: { companyName: "iProcure Africa", companyLogo: "" },
    location: "Nakuru, Kenya",
    type: "Full-Time",
    category: "Sales",
    salaryMin: 60000,
    salaryMax: 95000,
    experience: "2+ years",
    status: "open",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "iProcure is hiring an Agribusiness Sales Representative to grow its network of agro-dealer partners across the Rift Valley, helping smallholder farmers access quality inputs at fair prices.",
    responsibilities: [
      "Recruit and onboard new agro-dealer partners in the Nakuru and Rift Valley regions.",
      "Drive product sales targets for fertilisers, seeds, and agrochemicals.",
      "Conduct farmer training demonstrations alongside technical teams.",
      "Collect market intelligence on competitor pricing and farmer needs.",
      "Maintain accurate sales records in the iProcure mobile CRM.",
    ],
    requirements: [
      "2+ years of field sales experience, preferably in agribusiness or FMCG.",
      "Diploma or degree in Agriculture, Business, or a related field.",
      "Valid motorcycle licence; willingness to travel extensively in the field.",
      "Strong negotiation and relationship-building skills.",
      "Proficiency in both Kiswahili and English.",
    ],
  },
  {
    _id: "d12",
    title: "Accounts & Finance Officer",
    company: { companyName: "Nakuru Fresh Produce (SME)", companyLogo: "" },
    location: "Nakuru, Kenya",
    type: "Full-Time",
    category: "Finance",
    salaryMin: 55000,
    salaryMax: 80000,
    experience: "2+ years",
    status: "open",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Nakuru Fresh Produce is a mid-sized horticultural exporter supplying supermarkets in Nairobi and export markets in Europe. We need a Finance Officer to manage our day-to-day accounting, payroll, and KRA compliance.",
    responsibilities: [
      "Prepare monthly management accounts and cash flow statements.",
      "Process payroll for 60+ permanent and seasonal staff.",
      "File VAT, PAYE, and corporate tax returns via iTax on schedule.",
      "Reconcile bank statements and petty cash accounts weekly.",
      "Liaise with external auditors during the annual audit cycle.",
    ],
    requirements: [
      "CPA Part II or above (CPA-K preferred).",
      "2+ years of accounting experience in an SME or agricultural business.",
      "Proficiency with QuickBooks or Sage accounting software.",
      "Strong knowledge of KRA iTax system and Kenyan tax regulations.",
      "High integrity, discretion, and attention to detail.",
    ],
  },
  {
    _id: "d13",
    title: "Remote Product Manager",
    company: { companyName: "Twiga Foods", companyLogo: "" },
    location: "Remote",
    type: "Remote",
    category: "Product",
    salaryMin: 200000,
    salaryMax: 320000,
    experience: "5+ years",
    status: "open",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    description:
      "Twiga Foods is hiring a Remote Product Manager to lead its B2B marketplace product for urban informal retailers. You will own the roadmap, work with cross-functional squads, and use data to drive distribution efficiency across Kenya.",
    responsibilities: [
      "Own the product roadmap for the Twiga vendor marketplace and logistics platform.",
      "Define user stories, acceptance criteria, and success metrics with engineering squads.",
      "Prioritise the backlog using data from Amplitude and user interviews.",
      "Drive alignment between business stakeholders, design, and engineering.",
      "Launch features, measure outcomes, and iterate rapidly based on evidence.",
    ],
    requirements: [
      "5+ years of product management experience in a tech-enabled company.",
      "Demonstrated ability to ship 0-to-1 features and scale existing products.",
      "Strong quantitative skills — comfortable in SQL and product analytics tools.",
      "Experience working with or in African markets, especially Kenya, is a strong plus.",
      "Excellent written and verbal communication; thrives in a remote-first culture.",
    ],
  },
];

export default demoJobs;
